export enum Permissions {
    //User
    VIEW_USER = "VIEW_USER",
    ADD_USER = "ADD_USER",
    UPDATE_USER = "UPDATE_USER",
    DELETE_USER = "DELETE_USER",
    //Role
    VIEW_ROLE = "VIEW_ROLE",
    ADD_ROLE = "ADD_ROLE",
    UPDATE_ROLE = "UPDATE_ROLE",
    DELETE_ROLE = "DELETE_ROLE",
    ASSIGN_ROLE_TO_USER = "ASSIGN_ROLE_TO_USER",
    REMOVE_ROLE_FROM_USER = "REMOVE_ROLE_FROM_USER",
    //permission
    VIEW_PERMISSION = "VIEW_PERMISSION",
    ADD_PERMISSION = "ADD_PERMISSION",
    UPDATE_PERMISSION = "UPDATE_PERMISSION",
    DELETE_PERMISSION = "DELETE_PERMISSION",
    ASSIGN_PERMISSION_TO_ROLE = "ASSIGN_PERMISSION_TO_ROLE",
    REMOVE_PERMISSION_FROM_ROLE = "REMOVE_PERMISSION_FROM_ROLE",
    //workspace
    VIEW_WORKSPACE = "VIEW_WORKSPACE",
    ADD_WORKSPACE = "ADD_WORKSPACE",
    UPDATE_WORKSPACE = "UPDATE_WORKSPACE",
    DELETE_WORKSPACE = "DELETE_WORKSPACE",
};