export enum Roles {
    ADMIN = "ADMIN",
    USER = "USER",
    WORKSPACE_ADMIN = "WORKSPACE_ADMIN",
    WORKSPACE_MEMBER = "WORKSPACE_MEMBER",
    BOARD_ADMIN = "BOARD_ADMIN",
    BOARD_MEMBER = "BOARD_MEMBER",
};
